FROM registry.access.redhat.com/ubi10/ubi-minimal:10.0-1758699349@sha256:649f7ce8082531148ac5e45b61612046a21e36648ab096a77e6ba0c94428cf60

ARG VERSION=2.47.3-1

RUN microdnf upgrade --refresh -y && \
  microdnf install -y git-$VERSION.el10_0.x86_64 jq && \
  microdnf clean all && \
  git version && \
  jq --version

CMD ["bash"]
