FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1778461919@sha256:a41db89ac688576827fbd3e8e3ef145fd7f4db28d7f533c154f96224fcd20595

ARG VERSION=2.47.3-1

RUN microdnf upgrade --refresh -y && \
  microdnf install -y git-$VERSION.el10_0.x86_64 jq && \
  microdnf clean all && \
  git version && \
  jq --version

CMD ["bash"]
