FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1769677092@sha256:f8c05e3c6d15fea32e59635477c0f690e6d4b88a81924e8619f369e57306b701

ARG VERSION=2.47.3-1

RUN microdnf upgrade --refresh -y && \
  microdnf install -y git-$VERSION.el10_0.x86_64 jq && \
  microdnf clean all && \
  git version && \
  jq --version

CMD ["bash"]
