FROM registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1-1770179292@sha256:30bb24b61d037465bd0cf3721b72d0b610018f46bc337a64e404d52421a74e98

ARG VERSION=17.2.0

USER 0
RUN microdnf upgrade --refresh -y && \
  microdnf install -y jq && \
  microdnf clean all -y && \
  npm i release-please@${VERSION} -g && \
  release-please --version

USER 1001
ENTRYPOINT ["release-please"]
