# Build stage
FROM quay.io/hummingbird/nodejs:26-builder@sha256:cc4d4a6af58182daba5b70654b7bf306b80bbf3d2ab6fd28650850ea3450221f AS builder

ARG VERSION=17.6.1

# Install jq + deps
USER root
RUN dnf install -y jq && \
  dnf clean all -y

# Runtime stage
FROM quay.io/hummingbird/nodejs:26@sha256:3db22234183f3be2fc8cef13c175554c5e84bc955678c6e9b359a13f3a8106b7

USER root
RUN npm i release-please@${VERSION} -g && \
  release-please --version
USER ${CONTAINER_DEFAULT_USER}

# Copy jq + deps from builder
COPY --from=builder /usr/bin/jq /usr/bin/jq
COPY --from=builder /usr/lib64/libjq* /usr/lib64/
COPY --from=builder /usr/lib64/libonig* /usr/lib64/

ENTRYPOINT ["release-please"]
