FROM registry.access.redhat.com/ubi10/nodejs-22:10.0-1761020302@sha256:f8a43e16bc579770605ba1512522a5f70586dd8a8f13924d48e0f0ac61cabb17

ARG VERSION=17.1.3

USER 0
RUN dnf upgrade --refresh -y && \
  dnf install -y jq && \
  dnf clean all -y && \
  npm i release-please@${VERSION} -g && \
  release-please --version

USER 1001
ENTRYPOINT ["release-please"]
