FROM quay.io/hummingbird/core-runtime:2.42-builder@sha256:9c871831395eb27b162c2cba2c0327fcc6f6b0a546c4693168939b4e495eb5df AS builder

ARG VERSION=1.14.4

USER 0
RUN dnf install -y tar gzip && \
  curl -L https://github.com/coredns/coredns/releases/download/v${VERSION}/coredns_${VERSION}_linux_amd64.tgz | tar zxvf - && \
  ls -al coredns

FROM quay.io/hummingbird/core-runtime:2.42@sha256:3fadedf666f137f7d36a673fcf215307bf19bc56c12eb6a323674606eac3c5bf

COPY --from=builder /tmp/coredns /usr/local/bin/coredns

WORKDIR /etc/coredns
ENTRYPOINT ["coredns"]
