FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1776834797@sha256:2a4785f399dc7ae2f3ca85f68bac0ccac47f3e73464a47c21e4f7ae46b55a053 as builder

ARG VERSION=1.14.2

RUN microdnf install -y tar gzip && \
  curl -L https://github.com/coredns/coredns/releases/download/v${VERSION}/coredns_${VERSION}_linux_amd64.tgz | tar zxvf - && \
  ls -al coredns

FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1776834797@sha256:2a4785f399dc7ae2f3ca85f68bac0ccac47f3e73464a47c21e4f7ae46b55a053

COPY --from=builder /coredns /usr/local/bin/coredns

WORKDIR /etc/coredns
ENTRYPOINT ["coredns"]
