apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: gh-cli-build
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/paths-filter: "gh-cli/**"
    pipelinesascode.tekton.dev/task-1: "https://github.com/tektoncd/catalog/raw/main/task/git-clone/0.10/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://github.com/tektoncd/catalog/raw/main/task/buildah/0.9/buildah.yaml"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image-url
      value: quay.io/pabrahamsson/gh-cli:test
    - name: context
      value: gh-cli
  pipelineRef:
    params:
      - name: kind
        value: pipeline
      - name: name
        value: containers-build-pipeline
      - name: namespace
        value: container-builds
    resolver: cluster
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
