apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: goaccess-build
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image-url
      value: quay.io/pabrahamsson/goaccess:test
    - name: context
      value: goaccess
  pipelineRef:
    params:
      - name: kind
        value: pipeline
      - name: name
        value: containers-build-pipeline
      - name: namespace
        value: container-builds
    resolver: cluster
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
