FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1782191645@sha256:3948fdfe71007909b37faf48c52eda28bfab7c4e440d6f4d4619422d06ceeb4c

ARG HUGO_VERSION=0.163.3

RUN microdnf upgrade -y && \
    microdnf install -y rubygems ruby-devel gcc-c++ tar && \
    gem install -N ascii_binder asciidoctor-diagram asciidoctor-html5s rouge && \
    curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz | tar zxvf - -C /bin hugo && \
    hugo version

WORKDIR /blog
EXPOSE 1313
ENTRYPOINT ["hugo"]
CMD ["--logLevel", "info"]
