FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1776071394@sha256:7fabf2ff42ba1c2b3e4efcdd9ae25de0bce0592edf59151b41e58057b40898ce

ARG HUGO_VERSION=0.160.1

RUN microdnf upgrade -y && \
    microdnf install -y rubygems ruby-devel gcc-c++ tar && \
    gem install -N ascii_binder asciidoctor-diagram asciidoctor-html5s rouge && \
    curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz | tar zxvf - -C /bin hugo && \
    hugo version

WORKDIR /blog
EXPOSE 1313
ENTRYPOINT ["hugo"]
CMD ["--logLevel", "info"]
