FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1764604111@sha256:a13cec4e2e30fa2ca6468d474d02eb349200dc4a831c8c93f05a2154c559f09b

ARG HUGO_VERSION=0.152.2

RUN microdnf upgrade -y && \
    microdnf install -y rubygems ruby-devel gcc-c++ tar && \
    gem install -N ascii_binder asciidoctor-diagram asciidoctor-html5s rouge && \
    curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz | tar zxvf - -C /bin hugo && \
    hugo version

WORKDIR /blog
EXPOSE 1313
ENTRYPOINT ["hugo"]
CMD ["--logLevel", "info"]
