FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1770180557@sha256:a74a7a92d3069bfac09c6882087771fc7db59fa9d8e16f14f4e012fe7288554c

ARG VERSION=2.86.0

RUN  microdnf upgrade --refresh -y && \
  microdnf install -y jq git && \
  curl -LO https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.rpm && \
  rpm -Uvh gh_${VERSION}_linux_amd64.rpm && rm gh_${VERSION}_linux_amd64.rpm && \
  microdnf clean all && \
  gh version && \
  jq --version && \
  git --version

CMD ["bash"]
