FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1769521234@sha256:919a5a4c8595deb2f9c21b8a05ad027157f42feb6eed6b64efd1f4f455a5f759

ARG VERSION=2.86.0

RUN  microdnf upgrade --refresh -y && \
  microdnf install -y jq git && \
  curl -LO https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.rpm && \
  rpm -Uvh gh_${VERSION}_linux_amd64.rpm && rm gh_${VERSION}_linux_amd64.rpm && \
  microdnf clean all && \
  gh version && \
  jq --version && \
  git --version

CMD ["bash"]
