FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1-1776646707@sha256:8935d83eadb5c9f621c13f4dfab7e1bbd8d948317dc67157279911ede1013112

ARG VERSION=2.90.0

RUN  microdnf upgrade --refresh -y && \
  microdnf install -y jq git && \
  curl -LO https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.rpm && \
  rpm -Uvh gh_${VERSION}_linux_amd64.rpm && rm gh_${VERSION}_linux_amd64.rpm && \
  microdnf clean all && \
  gh version && \
  jq --version && \
  git --version

CMD ["bash"]
